import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Home, Clock, BarChart3 } from "lucide-react"; 
import { Toaster } from "react-hot-toast"; 
import Link from "next/link";
import { InteractionProvider } from "@/context/InteractionContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-slate-50`}>
        <InteractionProvider>
          <Toaster position="top-center" />
          
       
         {/* --- Navbar Section --- */}
            <Navbar />

          {/* --- Main Content Area --- */}
          <main className="flex-grow">
            {children}
          </main>

          {/* --- Footer Section --- */}
          <Footer />
       
        </InteractionProvider>
      </body>
    </html>
  );
}
